# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1191, 736)
        MainWindow.setMinimumSize(QtCore.QSize(1191, 736))
        MainWindow.setMaximumSize(QtCore.QSize(1191, 736))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frameHeader = QtWidgets.QFrame(self.centralwidget)
        self.frameHeader.setGeometry(QtCore.QRect(0, 0, 1191, 107))
        self.frameHeader.setStyleSheet("background-color:rgb(12, 31, 56);")
        self.frameHeader.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameHeader.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameHeader.setObjectName("frameHeader")
        self.label_2 = QtWidgets.QLabel(self.frameHeader)
        self.label_2.setGeometry(QtCore.QRect(330, 30, 781, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: white")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.frameHeader)
        self.label.setGeometry(QtCore.QRect(0, 0, 268, 107))
        self.label.setStyleSheet("background-color:rgb(12, 31, 56);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../Speed_Monitoring_System/GUI/ImageGUI/logo.png"))
        self.label.setObjectName("label")
        self.mainFrame = QtWidgets.QFrame(self.centralwidget)
        self.mainFrame.setGeometry(QtCore.QRect(0, 147, 1191, 531))
        self.mainFrame.setStyleSheet("")
        self.mainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 680, 1191, 31))
        self.frame.setStyleSheet("background-color:rgb(12, 31, 56);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.tabMonitoring = QtWidgets.QTabWidget(self.centralwidget)
        self.tabMonitoring.setGeometry(QtCore.QRect(0, 108, 1191, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.tabMonitoring.setFont(font)
        self.tabMonitoring.setStyleSheet("background-color:rgb(0, 33, 71)")
        self.tabMonitoring.setObjectName("tabMonitoring")
        self.tabRecognition = QtWidgets.QWidget()
        self.tabRecognition.setObjectName("tabRecognition")
        self.tabMonitoring.addTab(self.tabRecognition, "")
        self.tabGetImage = QtWidgets.QWidget()
        self.tabGetImage.setObjectName("tabGetImage")
        self.tabMonitoring.addTab(self.tabGetImage, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabMonitoring.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hệ Thống Giám Sát Phương Tiện Giao Thông"))
        self.label_2.setText(_translate("MainWindow", "Hệ Thống Giám Sát Phương Tiện Giao Thông"))
        self.tabMonitoring.setTabText(self.tabMonitoring.indexOf(self.tabRecognition), _translate("MainWindow", "Giám Sát"))
        self.tabMonitoring.setTabText(self.tabMonitoring.indexOf(self.tabGetImage), _translate("MainWindow", "Thống Kê"))
